#include<stdio.h>
#include<conio.h>
main()
{
  int x;
  clrscr();
  printf("Enter any number:");
  scanf("%d",&x);
  printf("%d*%d=%d\n",x,1,x*1);
  printf("%d*%d=%d\n",x,2,x*2);
  printf("%d*%d=%d\n",x,3,x*3);
  printf("%d*%d=%d\n",x,4,x*4);
  printf("%d*%d=%d\n",x,5,x*5);
  printf("%d*%d=%d\n",x,6,x*6);
  printf("%d*%d=%d\n",x,7,x*7);
  printf("%d*%d=%d\n",x,8,x*8);
  printf("%d*%d=%d\n",x,9,x*9);
  printf("%d*%d=%d\n",x,10,x*10);
  getch();



}